# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  get-runner:
    runs-on: ubuntu-latest
    outputs:
     RUNNER: ${{ runner.name }}
    steps:
      - run: echo "selected runner = ${{ runner.name }}"

  build:
    needs: get-runner
    runs-on: ${{ runner.name }}
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.20'

    - name: Build
      run: go build -v ./...

      
  test:
    runs-on: ${{ runner.name }}
    needs: 
    - get-runner 
    - build
    steps: 
    - name: Test
      run: go test -v ./...
      
  lint_vet:
    runs-on: ${{ runner.name }}
    needs: 
    - get-runner
    - build
    - test
    steps: 
    - name: go lint
      uses: norwd/golintr@v2.1.0

    - name: go vet
      run: go vet main.go
